/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as SettingsResetRouteImport } from './routes/settings.reset'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'
import { Route as SettingsAccountsRouteImport } from './routes/settings.accounts'
import { Route as ManageTransactionsRouteImport } from './routes/manage.transactions'
import { Route as ManageCategoriesRouteImport } from './routes/manage.categories'
import { Route as ManageAccountsRouteImport } from './routes/manage.accounts'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const SettingsResetRoute = SettingsResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountsRoute = SettingsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SettingsRoute,
} as any)
const ManageTransactionsRoute = ManageTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCategoriesRoute = ManageCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAccountsRoute = ManageAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/manage': typeof ManageRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/transactions': typeof TransactionsRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/reset': typeof SettingsResetRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/transactions': typeof TransactionsRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/reset': typeof SettingsResetRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/manage': typeof ManageRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/transactions': typeof TransactionsRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/reset': typeof SettingsResetRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/manage'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/transactions'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/reset'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/transactions'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/reset'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/manage'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/transactions'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
    | '/settings/accounts'
    | '/settings/categories'
    | '/settings/reset'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ManageRoute: typeof ManageRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignInRoute: typeof SignInRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/settings/reset': {
      id: '/settings/reset'
      path: '/reset'
      fullPath: '/settings/reset'
      preLoaderRoute: typeof SettingsResetRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/accounts': {
      id: '/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof SettingsAccountsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/manage/transactions': {
      id: '/manage/transactions'
      path: '/transactions'
      fullPath: '/manage/transactions'
      preLoaderRoute: typeof ManageTransactionsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/categories': {
      id: '/manage/categories'
      path: '/categories'
      fullPath: '/manage/categories'
      preLoaderRoute: typeof ManageCategoriesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/accounts': {
      id: '/manage/accounts'
      path: '/accounts'
      fullPath: '/manage/accounts'
      preLoaderRoute: typeof ManageAccountsRouteImport
      parentRoute: typeof ManageRoute
    }
  }
}

interface ManageRouteChildren {
  ManageAccountsRoute: typeof ManageAccountsRoute
  ManageCategoriesRoute: typeof ManageCategoriesRoute
  ManageTransactionsRoute: typeof ManageTransactionsRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAccountsRoute: ManageAccountsRoute,
  ManageCategoriesRoute: ManageCategoriesRoute,
  ManageTransactionsRoute: ManageTransactionsRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountsRoute: typeof SettingsAccountsRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsResetRoute: typeof SettingsResetRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountsRoute: SettingsAccountsRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsResetRoute: SettingsResetRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ManageRoute: ManageRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignInRoute: SignInRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
