/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageTransactionsRouteImport } from './routes/manage.transactions'
import { Route as ManageCategoriesRouteImport } from './routes/manage.categories'
import { Route as ManageAccountsRouteImport } from './routes/manage.accounts'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTransactionsRoute = ManageTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCategoriesRoute = ManageCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAccountsRoute = ManageAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/manage': typeof ManageRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/manage': typeof ManageRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/manage': typeof ManageRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/manage/accounts': typeof ManageAccountsRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/transactions': typeof ManageTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/manage'
    | '/reports'
    | '/sign-in'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/manage'
    | '/reports'
    | '/sign-in'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/manage'
    | '/reports'
    | '/sign-in'
    | '/manage/accounts'
    | '/manage/categories'
    | '/manage/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ManageRoute: typeof ManageRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/transactions': {
      id: '/manage/transactions'
      path: '/transactions'
      fullPath: '/manage/transactions'
      preLoaderRoute: typeof ManageTransactionsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/categories': {
      id: '/manage/categories'
      path: '/categories'
      fullPath: '/manage/categories'
      preLoaderRoute: typeof ManageCategoriesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/accounts': {
      id: '/manage/accounts'
      path: '/accounts'
      fullPath: '/manage/accounts'
      preLoaderRoute: typeof ManageAccountsRouteImport
      parentRoute: typeof ManageRoute
    }
  }
}

interface ManageRouteChildren {
  ManageAccountsRoute: typeof ManageAccountsRoute
  ManageCategoriesRoute: typeof ManageCategoriesRoute
  ManageTransactionsRoute: typeof ManageTransactionsRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAccountsRoute: ManageAccountsRoute,
  ManageCategoriesRoute: ManageCategoriesRoute,
  ManageTransactionsRoute: ManageTransactionsRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ManageRoute: ManageRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
